services:
  traefik:
    image: traefik:v3.6.1
    command:
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.prodresolver.acme.email=killian.stein@aidalinfo.fr" ## Email variable
      - "--certificatesresolvers.prodresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.prodresolver.acme.keytype=RSA4096"
      - "--certificatesresolvers.prodresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.prodresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.prodresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.prodresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    user: root
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.ghaction-serveur1.lab-cesi.fr`) ## Récupération terraform
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=prodresolver
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    user: root
    volumes:
      - grafana-etc:/etc/grafana
      - grafana-data:/var/lib/grafana
    restart: always   

volumes:
  grafana-etc: {}
  grafana-data: {}
