apiVersion: v1
clusters:
- name: "k8s-par-unruffled-ganguly"
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJXakNDQVFHZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQVZNUk13RVFZRFZRUURFd3ByZFdKbGNtNWwKZEdWek1CNFhEVEkyTURJeU5ERXdNRGd4TkZvWERUTTJNREl5TkRFd01EZ3hORm93RlRFVE1CRUdBMVVFQXhNSwphM1ZpWlhKdVpYUmxjekJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTVlSQTFFcDB6MHpGZlVKCklmV2hrSTdtb3Y3WktUMkdRZWNxZFlDNyt0VzZMek9mcGVpOUE1dEJreVhzSXd6amF0bVJkYjFWRGJmQVNBWkYKUmFIWTcwbWpRakJBTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZApEZ1FXQkJSdDdxTlhyb1NTbm8veTdVamZ6MEVyZ29uWXhUQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQkhudU1HCisyOGo0QzFZK1ppRGljSklzVmJtZEJsY2EzMU9oN0s1YkxGNitRSWdJMHRPVEpMOEpNcVk5MUE2bXZEc2tsM1cKS3Z0WVdRUGlmZXE2ZkhVbWxyVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://79617cd2-229c-4b16-8b64-faa5e218968f.api.k8s.fr-par.scw.cloud:6443
contexts:
- name: admin@k8s-par-unruffled-ganguly
  context:
    cluster: "k8s-par-unruffled-ganguly"
    user: k8s-par-unruffled-ganguly-admin
current-context: admin@k8s-par-unruffled-ganguly
kind: Config
preferences: {}
users:
- name: k8s-par-unruffled-ganguly-admin
  user:
    token: 2a1bbd1b-4c2d-486e-ad28-e30b61d93133