apiVersion: v1
clusters:
- name: "k8s-par-stoic-blackwell"
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJXekNDQVFHZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQVZNUk13RVFZRFZRUURFd3ByZFdKbGNtNWwKZEdWek1CNFhEVEkyTURJeU5UQTNOVGd4TWxvWERUTTJNREl5TlRBM05UZ3hNbG93RlRFVE1CRUdBMVVFQXhNSwphM1ZpWlhKdVpYUmxjekJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCRE95MFM1ZXhycHUxRGg4CmNydkMrNjVhbTBNQ2tJQ29ZNmd4RHNxMzQzUEozV29rL3lyTkIwSHk3VENFRDUyTW9hK21pbHk3TkdmUWlWSzEKNVVZai9wZWpRakJBTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZApEZ1FXQkJRZmRibElwVTVpWmRxY3VoNlMzOEFVVTVMTXBUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQXdqS1dHCjV0ODlwdysvdDJpdDFCWUp3RS9mSW1UeXl0Z08rMXBOZGRHdWNBSWhBT3FvSStZVmNaajE4eEVLVDdKcEU4TlQKRk1teEtXYW9xc0tvakpWRE1mV3YKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://6d7303dd-6b78-420c-bbdc-77f22c9b861a.api.k8s.fr-par.scw.cloud:6443
contexts:
- name: admin@k8s-par-stoic-blackwell
  context:
    cluster: "k8s-par-stoic-blackwell"
    user: k8s-par-stoic-blackwell-admin
current-context: admin@k8s-par-stoic-blackwell
kind: Config
preferences: {}
users:
- name: k8s-par-stoic-blackwell-admin
  user:
    token: e744b725-26f1-432a-affd-7afa011acb99